fix: logic for classes updated
KatsiarynaMizhuryna/JavaScript-classes-and-inheritance pull request #3
Opened 2023-05-10 09:24 UTC by KatsiarynaMizhuryna

link to the task: https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/classes-inheritance/classes-inheritance.md

2023-05-10 09:52 UTC, andron13 requested changes

2023-05-10 09:52 UTC, andron13 commented on main/inheritance.js
> +BaseBuilder.prototype.plus = function (...n) {
деструктуризации в es5 не было

2023-05-10 09:52 UTC, andron13 commented on main/inheritance.js
> +BaseBuilder.prototype.minus = function (...n) {};
BaseBuilder.prototype.minus = function (**...n**) {};
тоже самое

2023-05-10 09:53 UTC, andron13 commented
I took a quick look before the first error. check again and fix it. I'll look again later.

2023-05-10 15:44 UTC, KatsiarynaMizhuryna commented on main/inheritance.js
> +BaseBuilder.prototype.plus = function (...n) {
fixed

2023-05-10 21:54 UTC, andron13 reviewed
Сделай тестовые объекты для проверки. С большего всё очень неплохо выглядит. Если ты понимаешь что написала и тем более написала сама то это супер и 100баллов

2023-05-10 21:54 UTC, andron13 commented on main/inheritance.js
> +  });
Очень хорошо

2023-05-10 21:54 UTC, andron13 commented on main/inheritance.js
> +};
Очень хорошо

2023-05-10 21:54 UTC, andron13 reviewed
Сделай тестовые объекты для проверки. С большего всё очень неплохо выглядит. Если ты понимаешь что написала и тем более написала сама то это супер и 100баллов

2023-05-11 09:47 UTC, AndrejPodlubnyj approved these changes

2023-05-11 09:54 UTC, merged